name: Build Notebook Container

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout files in repo
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: bust old image
      uses: smartsquaregmbh/delete-old-packages@v0.3.0
      with:
        names: |
          lfs-binder

    - name: update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        # ^-- this could also be ${{ github.repository_owner }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY: ghcr.io
        BINDER_CACHE: true
        PUBLIC_REGISTRY_CHECK: true
